[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd vimenter * NERDTree
  let NERDTreeMinimalUI = 1
  let NERDTreeDirArrows = 1
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

#[[plugins]] # ステータスライン
#repo = 'itchyny/lightline.vim'
#hook_add = '''
#  let g:lightline = {
#  \   'colorscheme': 'snazzy'
#  \}
#'''

[[plugins]]
repo = 'munshkr/vim-tidal'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = "processing"

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'Yggdroot/indentLine'

